### ISSUE TITLE
Unable to Install NumPy

### ISSUE THREAD

**Issue by NathanEpstein** [nchammas/flintrock#111]
New flintrock user; trying to run a spark program which requires MLlib (which requires NumPy).

```
$ flintrock launch demo
$ flintrock login demo
$ flintrock run-command demo "sudo pip install numpy"
```

Which results in the following error:

```
Command "/usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-gt5hdD/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-c01fm5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-gt5hdD/numpy
```

Additional Info:
 - Using default config for flintrock (aside from pem)
 - OSX 10.10.2
 - flintrock, version 0.4.0

**Comment by nchammas** [comment]
I believe if you login to the cluster and run the same pip install, you'll get the full error barf which indicates the problem is a missing gcc install.

So the solution is:

```sh
flintrock run-command demo 'sudo yum install -y gcc'
flintrock run-command demo 'sudo pip install -U pip'  # optional but recommended
flintrock run-command demo 'sudo pip install numpy'
```

Can you confirm?

**Comment by NathanEpstein** [comment]
Confirmed - thank you!

>

-- 
Nathan Epstein
(973) 985 - 8158
LinkedIn <https://www.linkedin.com/in/ne2210> | Github
<https://github.com/nathanepstein> | Technical Blog
<http://nathanepstein.github.io/> | @epstein_n
<https://twitter.com/Epstein_N>

**Comment by nchammas** [comment]
Great!
