### ISSUE TITLE
Spark sometimes fails to come up, getting stuck at "Configuring Spark master..."

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#129]
I've occasionally been hitting up against a strange network-related issue when launching new or, more frequently, when starting stopped clusters.

Basically, the launch or start gets stuck on this step:

```
[master.ip.address] Configuring Spark master...
```

When I look at the Spark master log, I often see binding errors like this:

```
16/07/18 02:49:59 WARN Utils: Service 'sparkMaster' could not bind on port 7077. Attempting port 7078.
```

Other times, I see strange errors about Spark being unable to resolve the DNS name of the master.

When this happens I can usually just log in to the cluster and try starting the master again, and things work fine. So the issue seems to fix itself after some wait.

Has anyone else seen this issue or have any idea as to what might be happening?

**Comment by nchammas** [comment]
Hmm, I am still occasionally seeing this, even after correcting the variables I was using in `spark-env.sh` per 0c9a24b.

I don't understand why Spark would randomly have issues binding to ports after the instance is just started up. Is it an EC2 issue?

Should I just increase the limit on retrying ports? But then the security group rules would be incorrect, since Spark would be working on different ports from what's configured in the rules.

I've also tried waiting longer after the instance comes up but before starting up the Spark master, and even 30 seconds doesn't seem to be enough to prevent this from happening all the time...

**Comment by nchammas** [comment]
Does anyone more familiar with the Linux network stack know if there is something specific I should wait for on bootup before trying to start Spark up? Something that would be responsible for allowing Spark to bind ports?

**Comment by kruhly** [comment]
Hello,

We have an automated use case were we are batch processing and there is a random amount of time between batches. It could be several days or several minutes. We are using the standalone version 0.8.0 called  in various subprocesses in a python2.7 project. 

We are seeing the 

`Configuring spark master`

hang with the binding error, 

`java.net.BindException: Cannot assign requested address: Service 'sparkMaster' failed after 16 retries (starting from 7077)!`

regularly when the time between a stop/start or  destroy/launch is short and for the destroy/launch sequence the cluster configuration is the same. From limited testing the failure to bind  occurs when the terminated cluster still appears in the AWS console  and it is < 10 minutes between the time the cluster was destroyed and the time the (re)launch occurs.  Changing configuration for the (re)launch like the instance type, spot price or from spot instances to on-demand instances does not seem to trigger the exception when the interval is short. 

We have not experienced the DNS issue you mentioned. 

Unfortunately, we don't have any significant leads as to the cause of the problem.

Could you elaborate on what you did to restart the master after the exception? 

Thanks,

Rob

**Comment by nchammas** [comment]
> Could you elaborate on what you did to restart the master after the exception?

I did the same as you: simply start the master after a brief wait. 😞 

I don't have any new leads either on what the root problem is here, but I am starting to think that we should just implement a band-aid where Flintrock simply tries to start the master again if it detects Spark has taken a long time to start up.

**Comment by kruhly** [comment]
I think an internal band-aid, given the lack of evidence for a permanent fix, would be very helpful for our use case.
