### ISSUE TITLE
Add checks at startup for required commands

### ISSUE THREAD

**Issue by sylvinus** [nchammas/flintrock#132]
* Flintrock version: 0.5.0
* Python version: 2.7.9
* OS: Debian Jessie

I'm using flintrock inside Docker and didn't have SSH installed yet. Flintrock crashed because it calls `ssh-keygen` at some point.

This is not critical, but it would be great to validate the environment a bit at startup to avoid crashing later.

thanks!

**Comment by nchammas** [comment]
Thank you for reporting this @sylvinus. I completely agree.

External dependencies that Flintrock should validate upfront are, I believe, currently just these two:
* `ssh`
* `ssh-keygen`
