### ISSUE TITLE
Add datetime in the output?

### ISSUE THREAD

**Issue by sylvinus** [nchammas/flintrock#133]
One of Flintrock's strenghts is definitely its speed, so wouldn't it make sense to show the datetime before each output line, to be able to see how much time each operation took and maybe give hints on how to optimize it further?

**Comment by nchammas** [comment]
This is a good suggestion.

Flintrock today already shows the total time any given operation took. A breakdown for the individual "stages", so to speak, would definitely be interesting for me and for contributors like me who are obsessed with speed.

Perhaps stats like median and max time taken for tasks in each stage (e.g. configuring ephemeral storage; installing Spark; etc.) can be shown is some minimal and unobtrusive way.

I think this fits best when it is implemented as part of #27. I would prefer not to add more to the already busy output, e.g. during launches.

Does that sound good to you?

**Comment by sylvinus** [comment]
Yes! I agree it's most interesting after the launch for analysis, not necessarily while it's being done.

**Comment by nchammas** [comment]
Just realized that this request is already covered as part of #47. Closing this in favor of that issue.
