### ISSUE TITLE
Ensure Java >= 8 on launched nodes

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#143]
As raised in #142, Spark 2.0 deprecates support for Java 7. Furthermore, lots of Catalyst/Tungsten optimizations are enabled by running on Java 8.

Flintrock should, by default, ensure that all launched nodes have Java 8 or higher installed and configured to be the default.

If the user uses an AMI that already has this setup, Flintrock should detect that and do nothing.

**Comment by nchammas** [comment]
We should probably do this by having an `ensure_java8()` function inside of `core.py` that takes an SSH client as input and makes sure the host on the other end has Java 8 or higher. We should use this function anytime new instances are created--i.e. during initial launch or when slaves are added to an existing cluster.

**Comment by serialx** [comment]
Do you plan to do this? Or is this issue available for anyone to tackle on? :)

**Comment by nchammas** [comment]
PRs are welcome. 👍 Thanks for asking!

I suggest waiting until after #115 gets in to work on this, since that will affect how this feature is implemented.

**Comment by serialx** [comment]
Okay. I'll work on this as soon as the PR is merged.
