### ISSUE TITLE
Flintrock: launching cluster with my own AMI causes setup to not finish

### ISSUE THREAD

**Issue by c4goldsw** [nchammas/flintrock#159]
I'm attempting to launch a cluster using one of my own AMIs, which is publicly accessible.  Upon launching the cluster, I get this output:

```
chris@Pure-Gold:~$ flintrock launch ami_test
Launching 2 instances...
[54.163.88.185] SSH online.
[54.145.255.80] SSH online.
[54.163.88.185] bash: line 30: /home/ec2-user/.ssh/id_rsa: Permission denied
```

So, one of the nodes (the master I assume) lacks root permissions at some point when it should have root permissions.  Any ideas?

**Comment by nchammas** [comment]
What user are you connecting to the hosts with?

If you login to the master, what does `ls -l /home/ec2-user/.ssh/` return?

**Comment by c4goldsw** [comment]
Hey, thanks for the reply.  I'm just using ```ec2-user```.  Running ```ls``` on that directory returns
```
total 8
-rw------- 1 ec2-user ec2-user  795 Oct 24 02:35 authorized_keys
-r-------- 1 ec2-user ec2-user 1676 Oct 18 01:14 id_rsa
[ec2-user@ip-172-31-23-153 ~]$ 
```

**Comment by nchammas** [comment]
Hmm, that's strange.

1. What is your AMI based on, and how is it different from, say, the default Amazon Linux AMI?
2. If you launch a Flintrock cluster with the default Amazon Linux AMI, does it work for you? What differences do you see compared to your AMI when you run `ls -l /home/ec2-user/.ssh/`?

**Comment by c4goldsw** [comment]
1. My AMI is simply a saved image of the default Amazon Linux AMI after adding some data / source code.  As I don't want a cluster to run continuously, I want to be able to save the work I've done in an AMI and be able to load it at a later point.

2. When I use the default AMI, everything's fine.  Here are the content's of .ssh (on a cluster loaded from the default AMI):

```
[ec2-user@ip-172-31-18-116 ~]$ ls -l /home/ec2-user/.ssh
total 12
-rw------- 1 ec2-user ec2-user  795 Oct 19 01:44 authorized_keys
-r-------- 1 ec2-user ec2-user 1676 Oct 19 01:44 id_rsa
-rw-r--r-- 1 ec2-user ec2-user  444 Oct 19 01:45 known_hosts
[ec2-user@ip-172-31-18-116 ~]$ 
```

**Comment by nchammas** [comment]
OK, another thing to check are the permissions on the `.ssh/` directory itself.

Otherwise, I'm not sure what's going on here.

**Comment by nchammas** [comment]
@c4goldsw - Any new findings on your end regarding this issue?

**Comment by c4goldsw** [comment]
@nchammas Hey there, I apologise for the late reply.  I just did ```chmod 777 id_rsa``` and that fixed that issue.  After that, when launching using an AMI created from a Flintrock cluster, I ran into errors during the installation of spark (since it was already installed leading to ```[dir] already exists``` errors), which I resolved by launching with ```--no-install-spark```.

Overall, this issue seems to be that I wasn't using an option that assumes the instance is being launched from a configured AMI.  Is there such an option?  I didn't notice one in the source.

**Comment by nchammas** [comment]
What do you mean by "configured AMI"? Configured in what way exactly?

As you pointed out, Flintrock lets you skip installing Spark or HDFS. If you do, the setup it does is mostly limited to installing dependencies or configuring firewall rules. In other words, if you specify `--no-install-spark` and `--no-install-hdfs` (the latter of which is the default), Flintrock shouldn't be doing much.

So I'm curious as to what exactly is still going wrong there and how you might like Flintrock's behavior to change.

**Comment by c4goldsw** [comment]
So, here's what I'm doing:

1. I launch a cluster using Flintrock.
2. I do some work on that cluster, then go to save my progress using an AMI.  This is what I mean by "configured" - the image is of a machine that's been setup / configured by Flintrock.
3. At a later point, I attempt to launch a cluster from my saved AMI.  If I run ```flintrock launch [cluster] --no-install-spark```, the cluster setup still fails due to permissions on ```id_rsa```.  If I set the permissions of ```id_rsa``` to ```777``` before creating the image, then during setup, no problems are encountered.  I don't know what ```id_rsa``` contains, but I assume that Flintrock has to edit it during the setup process.

All in all, it'd be nice if Flintrock can support launching clusters from AMIs of a cluster it already setup previously.

**Comment by serialx** [comment]
I think this has to do with `setup_node` function in [this code][1].  Since the first install, `id_rsa` file is created with 400 permission.  This is a read-only permission.  So when the image is created with this state, next `flintrock launch` command will call `setup_node` again.  When that happens, `echo {private_key} > ~/.ssh/id_rsa` will fail because the file already exists and is read-only.

@c4goldsw Current workaround seems to remove `~/.ssh/id_rsa` file before building the AMI.  Should you test it, tell us it it works.

[1]: https://github.com/nchammas/flintrock/blob/master/flintrock/core.py#L563

**Comment by c4goldsw** [comment]
@serialx Deleting ```id_rsa``` works.   Thank you for the support.
