### ISSUE TITLE
Add support for adding or removing nodes from an existing Flintrock cluster

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#16]
You have a Flintrock cluster and you just want to add or remove a few nodes. Right now you either have to do that manually or you have to destroy your cluster and start over.

We should allow users to add or remove nodes from an existing cluster. This is a little tricky because the following things need to be take care of:

  - [ ] Spark, HDFS, and other installed services need to be reconfigured correctly to account for the added or removed nodes.
  - [ ] We should not support multiple masters or replacing the master.
  - [ ] Flintrock needs to detect the existing cluster configuration to know how to configure any added slaves. For example, what version of Spark should be installed?
 - [ ] A new SSH key for intra-cluster communication needs to be generated, or the existing one needs to somehow be reused for the new nodes.

  We will probably need to add some basic Flintrock manifest file to the master on launch which captures these details. That way Flintrock can automatically detect the cluster configuration and add nodes correctly.

Work on this issue depends on #8.

**Comment by engrean** [comment]
When using EMR, we use this feature all of the time. We might start our cluster out at 200 nodes, run a job, then grow it 600 nodes and run another job and then grow it 1200 nodes. We then shrink it down to 100 or even 50 nodes for the rest of the day.
