### ISSUE TITLE
Adding custom tags

### ISSUE THREAD

**Issue by lwoloszy** [nchammas/flintrock#182]
First off, thank you for this awesome package. I've been using it extensively for the last couple of months and it's been wonderful.

At my work, we label launched ec2 instances with additional tags for book-keeping purposes. Is there any interest to add that functionality to flintrock? Right now, the only tags flintrock uses are flintrock-role and Name and there's no way to append custom tags. I'm happy to take a stab if you think it's a worthwhile addition.

**Comment by nchammas** [comment]
Hi @lwoloszy and thank you for the kind words. They keep this project alive.

This seems like a reasonable request. We already support assigning arbitrary security groups to launched clusters, and assigning arbitrary tags seems like a closely related feature that would be useful for organizing resources.

If you want to take a stab at this, it might be good to closely model your work after how we handle user-specified security groups.
