### ISSUE TITLE
2. how to add/launch a  hybrid cluster

### ISSUE THREAD

**Issue by xiandong79** [nchammas/flintrock#215]
1. how to add new slaves to an existing cluster with flintrock? 

```
$ flintrock --help


Commands:
  add-slaves     Add slaves to an existing cluster.

```

2. how to add/launch a  hybrid cluster, i.e.,  4 machines with m4.large + 4 machines with m3.xlarge, even with 2 GPU machines with g2.lagre?

**Comment by nchammas** [comment]
Hi @xiandong79! It looks like you answered your first question.

With regards to the second question, it's currently not possible to launch a cluster with mixed instance types. There are a few related issues about this: #166, #138, #199.

I recommend following #199 for further updates on this issue. Before supporting arbitrary mixes of instance types (which I think is unlikely), we'd first want to support simply having the master and slaves be different instance types.
