### ISSUE TITLE
Add an option to wait for cluster destruction

### ISSUE THREAD

**Issue by alexandrnikitin** [nchammas/flintrock#229]
At the moment flintrock doesn't wait for instances termination. It could be useful to add an option (or even force it) to wait for instances to end up at terminated state.

**Comment by nchammas** [comment]
I think this could be helpful, but to help motivate the issue could you provide some use cases where someone would want to wait for cluster termination?

**Comment by alexandrnikitin** [comment]
@nchammas Thank you for your reply! Yes, I have a particular use case. There is a limit on number of running instances on AWS. There is a job that destroys the cluster after it finishes. There's another job that starts right after the second, but it can't launch a cluster because there are still instances in terminating state, and total number exceeds the limit. As a workaround: a `sleep` and additional checks on launch help. I was thinking about the `wait_for_state('terminated`)` call by default: https://github.com/alexandrnikitin/flintrock/commit/c8d23c807eed59089c12a5e5d2f83613b35d7c1b

**Comment by nchammas** [comment]
Makes sense to me. Perhaps we could put this behind an option:

```sh
flintrock destroy --wait <cluster_name>
```

And leave the default `destroy` behavior as-is.

What do you think?

**Comment by alexandrnikitin** [comment]
I don't have strong opinion on which way is better. Intuitively I think that waiting by default is better with `--no-wait` option. Do you think it needs a timeout option in addition?

**Comment by nchammas** [comment]
After thinking a bit more about this, I agree that it's better to have the default behavior be to wait and add a `--no-wait` option.

By waiting by default, you can chain actions after the destroy without having to cobble together sleep statements or polling for status. And it also fits the semantics of the operation--`destroy` won't return until the cluster is fully destroyed.

For simplicity, I don't think we need a timeout to start.

Would you like to submit a PR for this?

**Comment by alexandrnikitin** [comment]
I'm happy to. Here it is #231
I've been thinking about this, and I think it's fine to `wait_for_state('terminated)` by default. It's consistent with other commands: launch, stop, start.
