### ISSUE TITLE
PyYaml dependency (3.12) incompatible with Python 3.7

### ISSUE THREAD

**Issue by Maldus512** [nchammas/flintrock#267]
* Flintrock version: 0.8.0
* Python version: 3.7.0
* OS:  Arch Linux (4.17.11-arch1 x86_64)

I don't know if you are aware of this, but the latest version of flintrock fails to build with Python 3.7.0
I was experimenting with it yesterday and after I was finished I carelessly launched a system upgrade; apparently PyYaml 3.12 (the version currently used by flintrock) is not compatible with Python 3.7 (referencing [this issue](https://github.com/yaml/pyyaml/issues/126)), and I had to fall back to 3.6 to work with flintrock again.

PyYaml 3.13 on the opposite works with the newest version. I fixed my problem, but maybe it would be best to update the PyYaml dependency from 3.12, if there are no inherent problems with that?

**Comment by nchammas** [comment]
Agreed, this is a necessary upgrade. I intended to do it as part of #258, but that has been blocked on Travis CI supporting Python 3.7.

If you want to submit a PR just upgrading PyYAML to 3.13, that would be great. Otherwise, I'll get to this soon.
