### ISSUE TITLE
Hive support?

### ISSUE THREAD

**Issue by concretevitamin** [nchammas/flintrock#275]
Hi, 

Thanks for the awesome work on this project.  It seems to me by default Hive dependencies are not included, and there's no option to turn it on: https://github.com/nchammas/flintrock/blob/master/flintrock/services.py#L313.

Is there a workaround?  Any chance this can get patched?

**Comment by nchammas** [comment]
Closing this due to its age. I believe the release versions of Spark (as opposed to the ones built from git) that Flintrock uses all have Hive included. If I'm mistaken, @concretevitamin, feel free to reopen this issue.
