### ISSUE TITLE
ssh and eliptic curve issues

### ISSUE THREAD

**Issue by thagorx** [nchammas/flintrock#289]
* Flintrock version: 0.1.1
* Python version: 3.6
* OS: xubuntu 18.04

I have some troubles with connecting via ssh to my flintrock cluster. When I launch a new cluster I get the following deprecation messages:
```
0 of 2 instances granted. Waiting...
All 2 instances granted.
/usr/local/lib/python3.6/dist-packages/paramiko/ecdsakey.py:164: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.ecdsa_curve.curve_class(), pointinfo
/usr/local/lib/python3.6/dist-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/usr/local/lib/python3.6/dist-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/usr/local/lib/python3.6/dist-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
[54.92.199.59] SSH online.
[3.81.58.118] SSH online.
```
everything setups without any further issues and I can login via `flintrock login my_cluster`
and I get the `Warning: Permanently added '54.92.199.59' (ECDSA) to the list of known hosts.`
messages. I can login and out without issues.

The troubles start when I then try to ssh into the master outside of flintrock I get asked again to add the master to the list of know host

```
The authenticity of host 'ec2-54-92-199-59.compute-1.amazonaws.com (54.92.199.59)' can't be established.
ECDSA key fingerprint is SHA256:jcrEtNa62Gr9o27MUR7R6LRFYEoIHYzlGambV3ECdkQ.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'ec2-54-92-199-59.compute-1.amazonaws.com' (ECDSA) to the list of known hosts.
```

and the first sessions works without any Issues. But when I try to connect again or do an rsync or anything else where I authenticate via ssh like this:
`ssh -i '~/.ssh/my_launch_key.pem' ec2-user@ec2-54-92-199-59.compute-1.amazonaws.com`

I get: 
`ec2-user@ec2-54-92-199-59.compute-1.amazonaws.com: Permission denied (publickey).`

samething when I try to use `flintrock login my_cluster` I get:
`ec2-user@54.92.199.59: Permission denied (publickey).`

my guess is it has something to do with the deprecation warnings in `paramiko`

**Comment by nchammas** [comment]
Hey @thagorx, some questions for you.

1. Just to confirm, do you mean your Flintrock version is 0.11?
2. What's the AMI you're selecting in your Flintrock config?
3. If it's not an Amazon Linux AMI, can you try again with that?

We could try bumping the version of Paramiko that Flintrock uses and see if that helps. If you'd like, I suggest trying that out in a PR. I can guide you.

**Comment by thagorx** [comment]
Hey nchammas yeah I meant 0.11.
But it seems to be a problem with my AMI though it is updated to the newest version when I try it with the base AMI `ami-0b8d0d6ac70e5750c` the error is not reproducible.

and contributing to flintrock is still on my list but as a phd student time is a rare thing ... anyway I think these will be the last calculations for my thesis hopefully afterwards I have time to do things for "fun" :) 
Anyway thanks for developing this tool it helps me out tremendously!

**Comment by thagorx** [comment]
Okay looks like we go further down the rabbit hole.
I tried to rebuild my cluster launch process with the base AMI `ami-0b8d0d6ac70e5750c`

now I don't when I authenticate to the master via SSH everything still works I can login via ssh or `flintrock login my_cluster`
but afterwards I'm unable to login into the slaves. Either via flintrock or directly. I just get the following error msg:
`ec-user@ec2-52-91-74-200.compute-1.amazonaws.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).`

So just to recap I get the above error when: 
I create the cluster then login into the master via `ssh -i './.ssh/my_key.pem' ec-user@master` afterwards I still can ssh into the server but no longer ssh into the slaves either directly or via flintrock.

So just to recap I get the above error when: 
I create the cluster then login into the master via `ssh -i './.ssh/my_key.pem' ec-user@master` afterwards I still can ssh into the server but no longer ssh into the slaves either directly or via flintrock.

**Comment by nchammas** [comment]
It looks like you have a bad config. `ec-user` is probably not the username you want. 😄

**Comment by thagorx** [comment]
yeah my bad :D
