### ISSUE TITLE
Gracefully handle interrupted launches: allow flintrock caller to more easily idenify instances

### ISSUE THREAD

**Issue by rlaabs** [nchammas/flintrock#339]
I typically call flintrock as a subprocess, sometimes (eg when the wait for spot requests is too long), the subprocess times out. If this happens before the tags are set in ec2.launch() it is difficult to identify the instances that need to be cleaned up.

Would you be open to a PR that sets the user defined tags in the earlier ec2._create_instances() call?

I'm also working on a PR for the interrupted launch related #183 , but it may be best to split this one out?

* Flintrock version: 2.0.0.dev0
* Python version: 3.9.2

**Comment by nchammas** [comment]
Oh neat. I see that the EC2 API added this ability [in 2017](https://stackoverflow.com/a/43723682/877069), a couple of years after I wrote the initial cuts of `launch()` and `_create_instances()`.

I agree, it's better to add the tags as part of the operation that creates the instances, as opposed to in a separate step. 👍
