### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by TimHiggisonIFM** [nchammas/flintrock#343]
Hi @nchammas, would it be possible to cut a new Flintrock release with the existing changes? I'm interested in the private VPC changes that were merged in recently.

**Comment by nchammas** [comment]
Thanks for the gentle bump. Will get a new release out this week. Been meaning to do it for a month or so now. 😄

**Comment by TimHiggisonIFM** [comment]
Thanks Nick, you're the man!
