### ISSUE TITLE
Locked out at random. Never to recover. 

### ISSUE THREAD

**Issue by dorienh** [nchammas/flintrock#357]
It has happened to me multiple times that I am working with a cluster, all goes well for many hours. Then I ~/hadoop/sbin/stop-all.sh and  type 'exit'. The next day, flintrock login times out, also ssh times out. I have to throw away the cluster and reinstall. 

Is there any reason this could happen? I have already rebooted the instances in the EC2 dashboard. Is it locking out my ssh? 

I update my .aws credentials in ~/.aws/credentials (using aws academy account). 

* Flintrock version: 2.0.0
* OS: iOS 13.2.1

**Comment by nchammas** [comment]
Are you seeing in the AWS Console that the instances (especially the master instance) are still online when you try to SSH back in?

If SSH is timing out, then it seems like either the instance is down, or the security group rules changed somehow, or the SSH keys were changed somehow. There could be other possibilities of course, but of those three I feel like the first is most likely so that's where I would start.

**Comment by dorienh** [comment]
Yes I can see in the aws console that the instances are still running. 

I just rebooted my Mac and somehow I could login again. Not sure if the ssh was blocking me or so? Hope it doesn't happen again.

**Comment by dorienh** [comment]
Actually it came back the next day again, can't fix it now. I am at university on Eduroam, also tried mobile hotspot. Same thing. 

Even if I login with ssh it times out. My instances are running and 2/2 checks passed. 

When I `flintrock launch cluster8`

It now gives me: 

```
opt/homebrew/lib/python3.10/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
2023-03-31 09:28:20,913 - flintrock.ec2       - INFO  - Launching 4 instances...
2023-03-31 09:28:37,173 - flintrock.ec2       - DEBUG - 4 instances not in state 'running': 'i-09436562527109c97', 'i-09688b6b7e02ff6c0', 'i-0386eb57946f277df', ...
2023-03-31 09:28:42,171 - flintrock.ec2       - DEBUG - 4 instances not in state 'running': 'i-09436562527109c97', 'i-0386eb57946f277df', 'i-073c7c86259375c10', ...
2023-03-31 09:28:46,037 - flintrock.ec2       - DEBUG - 4 instances not in state 'running': 'i-09436562527109c97', 'i-0386eb57946f277df', 'i-073c7c86259375c10', ...
```

endlessly...

**Comment by nchammas** [comment]
What do you see in the console for these instances that don't seem to launch normally?

**Comment by dorienh** [comment]
Allow me a few days to see if it re-appears. I ended up doing a full reset of the aws environment (was using a learners lab).

**Comment by dorienh** [comment]
It just happened again. 

```
flintrock login cluster
/opt/homebrew/lib/python3.10/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ssh: connect to host 54.205.234.98 port 22: Operation timed out
```

My `~/.aws/credentials` are up to date. 

Looking at the dashbboard I see nothing special. [See screenshot here](https://www.dropbox.com/s/5iil3jttc7colli/cluster.png?dl=0). 

This is a fresh cluster. Only logged in once after launch. I setup pydoop/yarn. Then exited. A few days later try to login and it keeps timing out. 

Anything else I can check or reports I can generate?

**Comment by nchammas** [comment]
The lockout after some days smells like a firewall or network issue that's independent of Flintrock. But I'm not sure how to debug this because it could be so many different things. Do you have an AWS admin who can help you investigate?
