### ISSUE TITLE
AdoptOpenJDK.jfrog.io has been deprecated

### ISSUE THREAD

**Issue by rlaabs** [nchammas/flintrock#360]
https://adoptium.net/blog/2023/07/adoptopenjdk-jfrog-io-has-been-deprecated/

Scheduled brownouts happening now will cause cluster launches to fail. 

HDFS setup also doesn't seem to work with java-openjdk11 available from amazon-linux-extras

**Comment by ashizhou** [comment]
@rlaabs I came across the same problems as well. Have you managed to find a solution for it?

**Comment by rlaabs** [comment]
> @rlaabs I came across the same problems as well. Have you managed to find a solution for it?

@ashizhou Yes, I think the easiest workaround is to just install Java on your Amazon Machine Image; that way flintrock will skip the Java installation step where this is a problem.

I used the following:
-- OpenJDK 11.0.19
-- Spark 3.4.1
-- HDFS 3.3.6

Don't forget to set JAVA_HOME. That was the silly mistake I initially made.

**Comment by nchammas** [comment]
Thanks for reporting this and including a link to the deprecation announcement. Would you like to test the fix over on #361 before I merge it in?

**Comment by nchammas** [comment]
I'll go ahead and merge this PR in, actually, but of course feel free to test the fix in your environment any time. You can easily [install Flintrock directly from GitHub][1].

[1]: https://github.com/nchammas/flintrock/tree/5938d40747692dcee8aeaa6210bddd3424be1cbb#development-version

**Comment by dorienh** [comment]
> Yes, I think the easiest workaround is to just install Java on your Amazon Machine Image; that way flintrock will skip the Java installation step where this is a problem.
> 
> I used the following: -- OpenJDK 11.0.19

Forgive me for asking this noob question: how do I do this? Do I specify OpenJDK in the config file somewhere? Can I still use a standard aws linux 2 image?

**Comment by nchammas** [comment]
@dorienh - Are you still having problems installing Java on the latest version of Flintrock (2.1.0)?

If you'd like you make your own AMI, you'll need to work through [this guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html). And yes, your starting AMI -- the one from which you will create your own AMIs -- can be the standard Amazon Linux 2 image.
