### ISSUE TITLE
Allow clusters to be assigned IAM roles during launch

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#37]
When you launch a cluster you want to access a dataset somewhere, and that somewhere is often S3. You need credentials to access non-public locations on S3.

Instead of copying around AWS keys or doing some other janky setup, the Amazon-recommended way is to assign the instances in your cluster to an appropriate IAM role that lets them access what they need.

We should support this.

**Comment by engrean** [comment]
Following what seems to be the project naming standards and parameter names of AWS, --ec2-instance-profile-name seems like an appropriate name. It's long, but it if someone were to Google for "instance-profile-name", it would lead them to the AWS docs.

Feedback?

**Comment by nchammas** [comment]
Sounds good to me. :+1: 

Long option names are not a big obstacle in Flintrock since you can [persist your preferences to a file](https://github.com/nchammas/flintrock#configurable-cli-defaults) and avoid having to type them up. It's better to have descriptive names, in general.
