### ISSUE TITLE
Version 2.1.0 is not backward compatible with clusters created with version 2.0.0

### ISSUE THREAD

**Issue by sfcoy** [nchammas/flintrock#374]
* Flintrock version: 2.1.0
* Python version: 3.10
* OS: macOS Sonoma 14.4

This is an FYI. I don't expect it to be fixed.

It fails because the older clusters do not have any ec2 tags named "flintrock-name".

I fixed our clusters using the AWS CLI:

`aws ec2 create-tags --resources i-abc134... i-def456... --tags Key=flintrock-name,Value=foo`

where the cluster has a master node named `foo-master` and the slaves are all `foo-slave`.

**Comment by nchammas** [comment]
Thanks for sharing. Yes, this is a [deliberate design decision][1]:

> For starters, Flintrock provides no guarantee that clusters launched with one version of Flintrock can be managed by another version of Flintrock, and no considerations are made for any long-term use cases.

This choice is mostly in service of making it easier to maintain Flintrock over a long period of time. I'm glad the fix in your case was straightforward.

[1]: https://github.com/nchammas/flintrock/blob/c3dee6da06af4e6ca094ac6f0b4365d091c2541b/README.md#managing-permanent-infrastructure
