### ISSUE TITLE
Add support for HDFS module

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#40]
HDFS is a common part of people's "Big Data" workflows. Typically, their data lives there so that's where their work starts from.

In Flintrock's case, people are more likely to want to use HDFS as a temporary store for data pulled in from other places like S3 to speed up access to it by Spark. spark-ec2 directly supports this use case with both ephemeral and permanent HDFS installations provided on launched clusters.

Flintrock should offer something similar.

**Comment by ericmjonas** [comment]
The comments from shivaram were to follow the yarn code path but only set up hdfs, basically doing the steps in  `https://github.com/amplab/spark-ec2/blob/branch-1.5/ephemeral-hdfs/init.sh#L32` and for configs just grab whats in `https://github.com/amplab/spark-ec2/tree/branch-1.5/templates/root/ephemeral-hdfs/conf` and ignore the yarn, mapred ones
