### ISSUE TITLE
Enumerate alternatives to Flintrock

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#45]
[EMR supports Spark.](https://aws.amazon.com/blogs/aws/new-apache-spark-on-amazon-emr/) We should add a few lines to our README about when using Flintrock over EMR might make sense.

Potential reasons -- which I need to research and confirm -- include:
* Better command-line experience.
* Slightly faster support of newer Spark versions. (e.g. ~~EMR is still on 1.5.0.~~ EMR [now supports 1.5.2](https://aws.amazon.com/about-aws/whats-new/2015/11/apache-spark-1-5-2-and-new-versions-of-ganglia-monitoring-presto-zeppelin-and-oozie-now-available-in-amazon-emr/).)
* Support for deploying Spark at a specific git hash. (#25)
* More control over certain options.
* Support for alternate cloud providers. (Well, [eventually](https://github.com/nchammas/flintrock/issues/10).)
* Lower cost.

If you have your reasons one way or the other (EMR vs. Flintrock), share them here.

**Comment by engrean** [comment]
Pros for EMR:
  - As part of the spark-submit, can include the s3 location of the job's jar. (i.e. spark-submit ... s3://bucket/jars/my-spark-job.jar ....
  - I can kick my job off as an EMR step which is part of the AWS EMR API. I don't to ssh into the box and submit the job. 
  - The EMR step then reports on the status of the job and that status along w/ some simple stats like execution date/time, length of execution, and the entire job params are saved in the EMR history.
  - Part of the AWS EMR api allows for SSH access, but keeps all other ports closed down. They then have a nice EMR CLI where you can easily ssh-tunnel into the cluster to open the UI.
- It's easy to customize Spark settings when launching an EMR cluster.
- S3 reads and writes just work in my jobs.

Cons for EMR:
 - We've found from real-world experience that 2/3 of our monthly cost goes to EMR fees alone.
- Our jobs running on Spark Standalone run 25% faster than on Spark on YARN (EMR) with identical code and instance types. 
- Can't use Java 8, making our Java Spark jobs less fun to write.

**Comment by nchammas** [comment]
Thanks for sharing @engrean. As you become more familiar with Flintrock, feel free to add your observations about it versus EMR or other tools you've tried.

**Comment by nchammas** [comment]
I'm expanding this issue to cover adding a section, perhaps under [Motivation](https://github.com/nchammas/flintrock#motivation), to briefly list alternatives to Flintrock and why one might be interested in them.

Alternatives to mention include:
* EMR
* Juju, Salt, Ansible, etc.
* Databricks
* docker-machine (?)
* Various tools on Spark Packages under ["Deployment"](http://spark-packages.org/?q=tags%3A%22Deployment%22)

**Comment by nchammas** [comment]
I just checked in a change to the README to address part of this issue, but I didn't mention EMR. If the question of why one would want to use Flintrock over EMR comes up again, I may add a brief FAQ section to the README to address that.
