### ISSUE TITLE
Split out provider- and service-specific code to separate Python modules

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#6]
We should split up `flintrock.py` into a few modules that each focus on some area.

I think we should have a module for each provider (e.g. EC2, GCE) which covers all the major methods related to that provider like provisioning nodes, destroying resources, and so forth.

Additionally, we should have a Python module for each Flintrock module. A Flintrock module is a service or application you install on the cluster, like Spark. So methods that install, configure, or otherwise manage given a service like that go in one file.

**Comment by broxtronix** [comment]
I took a crack an this in #13.  It's just a straw-man at this point.  Definitely eager for feedback!
