### ISSUE TITLE
Configure Spark by default not to be noisy

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#60]
Spark by default spits out a lot of INFO messages. I rarely find them helpful. I wonder if the typical person does.

I think Flintrock should configure Spark by default not to spit out these messages. This can be done by setting the [root logging level](https://github.com/apache/spark/blob/59a501359a267fbdb7689058693aa788703e54b1/conf/log4j.properties.template#L19) to WARN via a Flintrock [template](https://github.com/nchammas/flintrock/tree/e391bb322e59c794b78ba25f4a460ddaa5368f78/templates).

**Comment by BenFradet** [comment]
I'll work on this once #122 gets merged.

**Comment by BenFradet** [comment]
@nchammas Should we make the log level customizable?
Because, for example, in [spark.ml's cross validator](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/tuning/CrossValidator.scala#L93-L129) the best parameters are logged at info level.

**Comment by nchammas** [comment]
Hmm, after thinking about this for a bit, I wonder if it's worth adding a new option just for logging level. And if INFO logging is sometimes useful, then perhaps we should just leave things as-is.

**Comment by BenFradet** [comment]
Fine by me.
