### ISSUE TITLE
Allow users to set the git commit to install Spark from as 'latest'

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#61]
Oftentimes, I imagine users wanting to install Spark from git may just care about getting the latest version on master to test a bug fix or new feature.

In that case, it's a hassle to have to look up the latest commit when Flintrock can just do it for you. Set the desired commit to `latest` and Flintrock will lookup the latest commit automatically.

There are 3 approaches we can take to implement a convenience feature like this:

1. Import some Python library for interacting with git and use that to query the latest version. Advantage: No implicit user dependencies. Disadvantage: It's another Flintrock dependency we have to vet.
2. Use `git` at the command line as such:

  ```
git ls-remote https://github.com/apache/spark master
  ```
  Advantage: Very simple. Disadvantage: We've created an implicit dependency on `git` being installed on the machine running Flintrock.
3. Query the GitHub API. Advantage: Still simple. Disadvantage: Now we have a dependency on GitHub for something that is strictly git functionality. This may not be a big deal since Spark itself, and likely most forks of it, are hosted on GitHub.

Depends on #25.

**Comment by BenFradet** [comment]
I'll take this one.
I see that you've taken the 2nd approach in #62, should I continue along those lines?

**Comment by nchammas** [comment]
In #62 I believe all the uses of `git` are on the cluster instances. There it makes sense since the cluster instances will need git anyway to clone Spark.

Here we are talking about the client machine running Flintrock, where I think it makes less sense to ask the user to install git just to use a feature of Flintrock.

Given that, I prefer approach 3.

It should be straightforward to do with Python's standard libraries, and we can provide an appropriate error message if people try to use `'latest'` with a repo not hosted on GitHub. I think it's a practical tradeoff.

**Comment by BenFradet** [comment]
Should `latest` become the default value for `--spark-git-commit`?

**Comment by nchammas** [comment]
Yep.
