### ISSUE TITLE
Spot instance launch failure with "bad parameters" not detected

### ISSUE THREAD

**Issue by ericmjonas** [nchammas/flintrock#83]
I tried to launch a spot instance cluster in us-west-2 with a custom AMI (that wanted a 40 GB root volume), and the launch hangs  in `waiting` even though the spot requests fail: 
```
jonas@c65:/data/jonas/suncast/suncast$ conda run -n py35 --offline -- flintrock --config flintrock.config.yaml launch frctest18
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata:
Requesting 5 spot instances at a max price of $1.0...
0 of 5 instances granted. Waiting...
0 of 5 instances granted. Waiting...
0 of 5 instances granted. Waiting...
0 of 5 instances granted. Waiting...
0 of 5 instances granted. Waiting...
0 of 5 instances granted. Waiting...
0 of 5 instances granted. Waiting...
0 of 5 instances granted. Waiting...
```
(etc)

looking at my EC2 console I see
![image](https://cloud.githubusercontent.com/assets/36626/13083354/79df5214-d489-11e5-9717-4dadb99e46f2.png)

and 
![image](https://cloud.githubusercontent.com/assets/36626/13083365/87ce99c0-d489-11e5-8d0f-3cbbb63964ae.png)

Is it possible to have flintrock catch and report the bad-parameters error?

**Comment by nchammas** [comment]
Thanks for the report. So it looks like there are 2 issues here.

One is that Flintrock should not be setting the root volume size when it's already 30GB or larger.

The second is that, as you point out, Flintrock is not catching when a spot request fails, whether it's due to bad parameters or something else for that matter. The relevant code is [here](https://github.com/nchammas/flintrock/blob/e163743fcc4d2187e786020c91052e67ece48c74/flintrock/ec2.py#L449-L458).

**Comment by nchammas** [comment]
Quick question about `ami-fba6bd9a`, since I'm trying to reproduce the issue you hit: Is that a publicly accessible AMI in `us-west-2`, or is it private to your Amazon account?

**Comment by ericmjonas** [comment]
Alas, it's private -- Nick is there an easy way to give you access?

On Tue, Feb 16, 2016 at 12:50 PM, Nicholas Chammas <notifications@github.com

**Comment by nchammas** [comment]
Hmm, there's probably a way to do that by specifying my Amazon account number in some AMI permissions dialog.

Did you create that AMI from a public AMI that has the same 40GB root volume?

**Comment by ericmjonas** [comment]
No, that was one of the main changes I made from the base AMI (along with
putting a ton of pre-built artifacts in that AMI).

On Tue, Feb 16, 2016 at 12:58 PM, Nicholas Chammas <notifications@github.com

**Comment by nchammas** [comment]
OK. You should be able to modify the AMI permissions from the EC2 web console to make it either public or accessible only to me.

**Comment by ericmjonas** [comment]
Nick can you pm me (jonas@ericjonas.com) your 12-digit numerical amazon ID?
(I am following the instructions in
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html
)

**Comment by nchammas** [comment]
Done.
