### ISSUE TITLE
Cannot install package pre-built for Hadoop 2.4

### ISSUE THREAD

**Issue by hhbyyh** [nchammas/flintrock#88]
There's no way to config which pre-built version to install for Spark 1.6.0.

**Comment by nchammas** [comment]
Correct, though you could easily hack this by modifying [this line](https://github.com/nchammas/flintrock/blob/1e582dcf7a2fb3912343e93ee4dac6c297f920cf/flintrock/services.py#L220-L221).

One of Flintrock's [anti-use cases](https://github.com/nchammas/flintrock#launching-out-of-date-services) is support for out-of-date versions of services like Hadoop. I've considered allowing users to specify the distribution of Spark to install, but I haven't found a good motivating use case for it. Generally, Flintrock targets the latest versions of everything.

What's your use case for wanting Spark built against Hadoop 2.4?

**Comment by hhbyyh** [comment]
We want to save the compute result to S3. Yet Hadoop 2.6 has problem with that.
You may check https://issues.apache.org/jira/browse/SPARK-7442 for more details.
Generally speaking, pre-built for Hadoop 2.4 can perfectly support writing to S3n directly while 2.6 cannot.

**Comment by nchammas** [comment]
Ah yes, that issue. (Funny, I was actually the one who reported it!)

I have a TODO on my list to deploy the additional JARs required to get Spark / Hadoop 2.6 working with S3, though I didn't create an issue for it here on GitHub yet.

If Flintrock automatically did that for you, would you still be interested in deploying Spark pre-built for Hadoop 2.4?

Alternately, I can expose the Spark profile as an option to get around this problem until [SPARK-7481](https://issues.apache.org/jira/browse/SPARK-7481) is resolved.

**Comment by ereed-tesla** [comment]
Alternatively, you can get the packages at runtime with (e.g.):
`pyspark --packages com.amazonaws:aws-java-sdk-pom:1.10.34,org.apache.hadoop:hadoop-aws:2.6.0`

This allows you to access S3n.

**Comment by nchammas** [comment]
Thanks for the tip @ereed-tesla! That'll be handy until we find a good solution for this issue, whether here or upstream.

**Comment by hhbyyh** [comment]
@ereed-tesla Thanks for the response. Do you happen to know how to deal with it if I'm using spark-submit.

**Comment by hhbyyh** [comment]
@nchammas All I want is to write to S3....

**Comment by ereed-tesla** [comment]
The same arg (--packages) works for spark-submit.

**Comment by nchammas** [comment]
It is now possible to change the Spark distribution by providing a custom source to download Spark from. For more details, see #125.
