### ISSUE TITLE
Look for Spark's make-distribution.sh script in its new location (plus its current one)

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#91]
As part of Spark 2.0, `make-distribution.sh` is [moving to a new location](https://github.com/apache/spark/pull/11522/files#diff-ba2c046d92a1d2b5b417788bfb5cb5f8). We use this script to [build Spark at a particular commit](https://github.com/nchammas/flintrock/blob/1e582dcf7a2fb3912343e93ee4dac6c297f920cf/flintrock/services.py#L250-L260).

Flintrock needs to look for this script in both the current and new locations, since the script will be in different places depending on what commit of Spark we checkout from git.

**Comment by BenFradet** [comment]
I'll take this one!
